// This file is automatically generated by typings-for-css-modules.
// Please do not change this file!
export const setup_security: string;
export const setupSecurity: string;
export const row: string;
export const col2: string;
export const help: string;
export const helpHeading: string;
export const helpItem: string;
export const wrapWord: string;
export const separator: string;
