// This file is automatically generated. Please do not change this file!
export const consoleLog: string;
export const consoleLogButton: string;
export const content: string;
export const footer: string;
export const fullscreen: string;
export const header: string;
export const left: string;
export const right: string;
